/**
 * Sofia Platform Catalog — 142 platforms with auth, signals & integration info
 * Source: docs/prompt/sofia_platforms_full.xlsx
 * Single source of truth for platform configurations
 */

import type {
  PlatformConfig,
  IntegrationPhase,
  SignalConfidence,
} from "../types/reputation"

export const PLATFORM_CATALOG: PlatformConfig[] = [
  // =========================================================================
  // DEVELOPPEMENT (17 plateformes)
  // =========================================================================
  {
    id: "github",
    name: "GitHub",
    icon: "github",
    color: "#4472C4",
    authType: "oauth2",
    website: "https://github.com",
    apiBaseUrl: "https://api.github.com",
    scopes: ["read:user", "repo"],
    dataPoints: [
      "commits",
      "streak",
      "repos",
      "langages",
      "PRs",
      "stars",
      "contributions",
    ],
    targetTopics: ["tech-dev", "entrepreneurship"],
    targetCategories: [
      "web-development",
      "ai-ml",
      "devops-cloud",
      "open-source",
      "web3-infra-dev",
      "startup-saas",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    rateLimitInfo: "5000 req/h authenticated",
    notes:
      "API publique pour profils publics. Scope read:user pour donnees privees.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    icon: "gitlab",
    color: "#FC6D26",
    authType: "oauth2",
    website: "https://gitlab.com",
    apiBaseUrl: "https://gitlab.com/api/v4",
    scopes: ["read_api"],
    dataPoints: [
      "commits",
      "pipelines",
      "merge-requests",
      "issues",
      "activite-projets",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development", "devops-cloud", "open-source"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Similaire GitHub. Fort signal DevOps. Bonne alternative pour devs enterprise.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    icon: "bitbucket",
    color: "#0052CC",
    authType: "oauth2",
    website: "https://bitbucket.org",
    apiBaseUrl: "https://api.bitbucket.org/2.0",
    dataPoints: ["repos", "commits", "PRs", "pipelines"],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development", "devops-cloud"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Moins utilise que GitHub mais signal valide, surtout en entreprise.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    icon: "stackoverflow",
    color: "#F48024",
    authType: "oauth2",
    website: "https://stackoverflow.com",
    apiBaseUrl: "https://api.stackexchange.com/2.3",
    dataPoints: [
      "reputation",
      "badges",
      "reponses-acceptees",
      "tags-dominants",
      "ratio-ask-answer",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: [
      "web-development",
      "ai-ml",
      "devops-cloud",
      "cybersecurity",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    rateLimitInfo: "25000 req/jour",
    notes:
      "Tags = specialisation exacte. Un des meilleurs signaux dev.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    icon: "huggingface",
    color: "#FFD21E",
    authType: "oauth2",
    website: "https://huggingface.co",
    apiBaseUrl: "https://huggingface.co/api",
    dataPoints: [
      "modeles-publies",
      "datasets",
      "spaces",
      "downloads",
      "likes",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["ai-ml"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "API publique. Signal AI/ML irrefutable.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "kaggle",
    name: "Kaggle",
    icon: "kaggle",
    color: "#20BEFF",
    authType: "oauth2",
    website: "https://kaggle.com",
    apiBaseUrl: "https://www.kaggle.com/api/v1",
    dataPoints: [
      "competitions",
      "medailles",
      "notebooks",
      "datasets",
      "rang",
    ],
    targetTopics: ["tech-dev", "science"],
    targetCategories: ["ai-ml", "mathematics", "data-science"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Medailles = validation communaute. Signal recrutement ML fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "npm",
    name: "npm Registry",
    icon: "npm",
    color: "#CB3837",
    authType: "public",
    website: "https://npmjs.com",
    apiBaseUrl: "https://registry.npmjs.org",
    dataPoints: [
      "packages-publies",
      "telechargements",
      "dependants",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Entierement public. Telechargements hebdo = usage reel.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "pypi",
    name: "PyPI",
    icon: "python",
    color: "#3775A9",
    authType: "public",
    website: "https://pypi.org",
    apiBaseUrl: "https://pypi.org/pypi",
    dataPoints: [
      "packages-publies",
      "downloads",
      "versions",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development", "ai-ml"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "pypistats.org API. Meme logique npm.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "replit",
    name: "Replit",
    icon: "replit",
    color: "#F26207",
    authType: "oauth2",
    website: "https://replit.com",
    apiBaseUrl: "https://replit.com/api",
    dataPoints: [
      "projets-crees",
      "forks",
      "runs",
      "projets-publics",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development", "lowcode-nocode"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Bon signal pour apprenants et devs juniors.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "devto",
    name: "Dev.to",
    icon: "devto",
    color: "#0A0A0A",
    authType: "oauth2",
    website: "https://dev.to",
    apiBaseUrl: "https://dev.to/api",
    dataPoints: [
      "articles-publies",
      "reactions",
      "commentaires",
      "tags",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development", "open-source"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "API ouverte. Tags des articles = specialisation precise.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "hashnode",
    name: "Hashnode",
    icon: "hashnode",
    color: "#2962FF",
    authType: "oauth2",
    website: "https://hashnode.com",
    apiBaseUrl: "https://gql.hashnode.com",
    dataPoints: [
      "articles",
      "tags",
      "followers",
      "reactions",
      "series",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development", "open-source"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "GraphQL API complete. Alternative Dev.to.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    icon: "hackernews",
    color: "#FF6600",
    authType: "public",
    website: "https://news.ycombinator.com",
    apiBaseUrl: "https://hacker-news.firebaseio.com/v0",
    dataPoints: [
      "points",
      "commentaires",
      "stories-soumises",
      "karma",
    ],
    targetTopics: ["tech-dev", "entrepreneurship"],
    targetCategories: ["web-development", "startup-saas"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Pas d'OAuth. API Firebase publique. Karma = signal qualite.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "leetcode",
    name: "LeetCode",
    icon: "leetcode",
    color: "#FFA116",
    authType: "public",
    website: "https://leetcode.com",
    apiBaseUrl: "https://leetcode.com/graphql",
    dataPoints: [
      "problemes-resolus",
      "streak",
      "rang",
      "difficulte-hard-medium-easy",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Endpoint GraphQL non officiel mais stable. Signal recrutement top.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "hackerrank",
    name: "HackerRank",
    icon: "hackerrank",
    color: "#00EA64",
    authType: "oauth2",
    website: "https://hackerrank.com",
    apiBaseUrl: "https://www.hackerrank.com/rest",
    dataPoints: [
      "certifications",
      "badges",
      "scores-par-domaine",
      "classement",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Certifications verifiables = signal fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "vercel",
    name: "Vercel",
    icon: "vercel",
    color: "#000000",
    authType: "oauth2",
    website: "https://vercel.com",
    apiBaseUrl: "https://api.vercel.com",
    dataPoints: [
      "projets-deployes",
      "frequence-deploiement",
      "frameworks",
      "domaines-custom",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development", "devops-cloud"],
    signalConfidence: "high",
    integrationPhase: 2,
    notes: "Signal fort devs frontend actifs.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "netlify",
    name: "Netlify",
    icon: "netlify",
    color: "#00C7B7",
    authType: "oauth2",
    website: "https://netlify.com",
    apiBaseUrl: "https://api.netlify.com/api/v1",
    dataPoints: [
      "sites-deployes",
      "builds",
      "formulaires",
      "fonctions",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["web-development"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Similaire Vercel.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "codepen",
    name: "CodePen",
    icon: "codepen",
    color: "#1E1F26",
    authType: "oauth2",
    website: "https://codepen.io",
    apiBaseUrl: "https://cpv2api.com",
    dataPoints: [
      "pens-publies",
      "forks-recus",
      "likes",
      "collections",
    ],
    targetTopics: ["tech-dev", "design-creative"],
    targetCategories: ["web-development", "generative-art"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Signal designers-developers (CSS art, animations).",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // DESIGN (10 plateformes)
  // =========================================================================
  {
    id: "figma",
    name: "Figma",
    icon: "figma",
    color: "#F24E1E",
    authType: "oauth2",
    website: "https://figma.com",
    apiBaseUrl: "https://api.figma.com/v1",
    scopes: ["files:read"],
    dataPoints: [
      "projets",
      "fichiers-edites",
      "commentaires",
      "collaborateurs",
      "plugins",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["ui-ux-design"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Meilleur signal design produit disponible.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "behance",
    name: "Behance",
    icon: "behance",
    color: "#1769FF",
    authType: "oauth2",
    website: "https://behance.net",
    apiBaseUrl: "https://api.behance.net/v2",
    dataPoints: [
      "projets-publies",
      "appreciations",
      "vues",
      "followers",
      "categories",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["illustration", "graphic-design", "creative-direction"],
    signalConfidence: "high",
    integrationPhase: 2,
    notes:
      "API Adobe. Categories = specialisation precise.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "dribbble",
    name: "Dribbble",
    icon: "dribbble",
    color: "#EA4C89",
    authType: "oauth2",
    website: "https://dribbble.com",
    apiBaseUrl: "https://api.dribbble.com/v2",
    dataPoints: [
      "shots-postes",
      "likes",
      "followers",
      "rebounds",
      "pro-account",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["ui-ux-design", "illustration", "creative-direction"],
    signalConfidence: "high",
    integrationPhase: 2,
    notes: "Signal design digital qualitatif.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "deviantart",
    name: "DeviantArt",
    icon: "deviantart",
    color: "#00E59B",
    authType: "oauth2",
    website: "https://deviantart.com",
    apiBaseUrl: "https://www.deviantart.com/api/v1/oauth2",
    dataPoints: [
      "deviations",
      "faves",
      "commentaires",
      "watchers",
      "galeries",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["illustration"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "API bien documentee. Large communaute illustration/fan art.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "sketchfab",
    name: "Sketchfab",
    icon: "sketchfab",
    color: "#1CAAD9",
    authType: "oauth2",
    website: "https://sketchfab.com",
    apiBaseUrl: "https://api.sketchfab.com/v3",
    dataPoints: [
      "modeles-3d",
      "vues",
      "likes",
      "followers",
      "categories",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["3d-modeling", "ar-vr-spatial"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "Excellent signal 3D artists.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "unsplash",
    name: "Unsplash",
    icon: "unsplash",
    color: "#000000",
    authType: "oauth2",
    website: "https://unsplash.com",
    apiBaseUrl: "https://api.unsplash.com",
    dataPoints: [
      "photos-uploadees",
      "telechargements",
      "vues",
      "collections",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["photography"],
    signalConfidence: "high",
    integrationPhase: 3,
    rateLimitInfo: "50 req/h",
    notes:
      "Telechargements = usage reel = qualite prouvee.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "flickr",
    name: "Flickr",
    icon: "flickr",
    color: "#0063DC",
    authType: "oauth1",
    website: "https://flickr.com",
    apiBaseUrl: "https://api.flickr.com/services/rest",
    dataPoints: [
      "photos-publiees",
      "vues",
      "faves",
      "groupes",
      "tags-exif",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["photography"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "EXIF data = type d'appareil = niveau de serieux.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "500px",
    name: "500px",
    icon: "500px",
    color: "#0099E5",
    authType: "oauth2",
    website: "https://500px.com",
    apiBaseUrl: "https://api.500px.com/v1",
    dataPoints: [
      "photos",
      "pulse-score",
      "affections",
      "vues",
      "categories",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["photography"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Pulse = score qualite automatique. Photographes serieux.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "itchio",
    name: "Itch.io",
    icon: "itchio",
    color: "#FA5C5C",
    authType: "api_key",
    website: "https://itch.io",
    apiBaseUrl: "https://itch.io/api/1",
    dataPoints: [
      "jeux-publies",
      "downloads",
      "ratings",
      "revenus",
    ],
    targetTopics: ["design-creative", "gaming"],
    targetCategories: [
      "illustration",
      "indie-art-games",
      "3d-modeling",
      "game-dev",
      "game-design",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Signal game designers et artistes pixel/indie.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "wattpad",
    name: "Wattpad",
    icon: "wattpad",
    color: "#FF6122",
    authType: "oauth2",
    website: "https://wattpad.com",
    apiBaseUrl: "https://api.wattpad.com/v4",
    dataPoints: [
      "histoires-publiees",
      "lectures",
      "votes",
      "followers",
      "genres",
    ],
    targetTopics: ["design-creative", "literature"],
    targetCategories: ["creative-writing"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal auteurs fiction.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // MUSIQUE (9 plateformes)
  // =========================================================================
  {
    id: "spotify",
    name: "Spotify",
    icon: "spotify",
    color: "#1DB954",
    authType: "oauth2",
    website: "https://spotify.com",
    authUrl: "https://accounts.spotify.com/authorize",
    tokenUrl: "https://accounts.spotify.com/api/token",
    apiBaseUrl: "https://api.spotify.com/v1",
    scopes: [
      "user-read-private",
      "user-top-read",
      "user-follow-read",
      "playlist-read-private",
    ],
    dataPoints: [
      "top-artists",
      "top-tracks",
      "genres",
      "playlists-creees",
      "podcasts",
    ],
    targetTopics: ["music-audio"],
    targetCategories: [
      "music-production",
      "djing",
      "music-culture",
      "podcast-audio",
    ],
    signalConfidence: "medium",
    integrationPhase: 0,
    notes:
      "Signal d'interet mais pas d'expertise. Combiner avec creation.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "lastfm",
    name: "Last.fm",
    icon: "lastfm",
    color: "#D51007",
    authType: "oauth2",
    website: "https://last.fm",
    apiBaseUrl: "https://ws.audioscrobbler.com/2.0",
    dataPoints: [
      "scrobbles-totaux",
      "artistes-top",
      "tags",
      "loved-tracks",
      "anciennete",
    ],
    targetTopics: ["music-audio"],
    targetCategories: [
      "music-production",
      "djing",
      "music-collecting",
      "music-culture",
    ],
    signalConfidence: "high",
    integrationPhase: 1,
    notes:
      "Historique long = passion durable. Tags = niche precise.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    icon: "soundcloud",
    color: "#FF5500",
    authType: "oauth2",
    website: "https://soundcloud.com",
    apiBaseUrl: "https://api.soundcloud.com",
    dataPoints: [
      "tracks-uploadees",
      "plays",
      "reposts",
      "commentaires",
      "followers",
      "sets",
    ],
    targetTopics: ["music-audio"],
    targetCategories: ["music-production", "sound-design", "music-business"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "Signal musiciens et DJs actifs. API bien maintenue.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "mixcloud",
    name: "Mixcloud",
    icon: "mixcloud",
    color: "#5000FF",
    authType: "oauth2",
    website: "https://mixcloud.com",
    apiBaseUrl: "https://api.mixcloud.com",
    dataPoints: [
      "mixes-uploades",
      "ecoutes",
      "followers",
      "duree",
      "genres-tagues",
    ],
    targetTopics: ["music-audio"],
    targetCategories: ["djing"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes: "Excellent pour valider expertise DJ/radio.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "deezer",
    name: "Deezer",
    icon: "deezer",
    color: "#00C7F2",
    authType: "oauth2",
    website: "https://deezer.com",
    apiBaseUrl: "https://api.deezer.com",
    dataPoints: [
      "playlists",
      "artistes-favoris",
      "albums",
      "historique",
      "genres",
    ],
    targetTopics: ["music-audio"],
    targetCategories: ["music-culture"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Moins riche que Spotify mais API plus ouverte.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "discogs",
    name: "Discogs",
    icon: "discogs",
    color: "#333333",
    authType: "oauth1",
    website: "https://discogs.com",
    apiBaseUrl: "https://api.discogs.com",
    dataPoints: [
      "collection-vinyles",
      "ventes",
      "want-list",
      "genres-collectes",
    ],
    targetTopics: ["music-audio", "food-lifestyle"],
    targetCategories: ["music-collecting", "djing"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "Signal collector/crate digger ultra-precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "listenbrainz",
    name: "ListenBrainz",
    icon: "listenbrainz",
    color: "#353070",
    authType: "oauth2",
    website: "https://listenbrainz.org",
    apiBaseUrl: "https://api.listenbrainz.org",
    dataPoints: [
      "scrobbles",
      "artistes",
      "releases",
      "statistiques-temporelles",
    ],
    targetTopics: ["music-audio"],
    targetCategories: ["music-collecting", "music-culture"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Alternative open source Last.fm. Donnees completes.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "musicbrainz",
    name: "MusicBrainz",
    icon: "musicbrainz",
    color: "#BA478F",
    authType: "oauth2",
    website: "https://musicbrainz.org",
    apiBaseUrl: "https://musicbrainz.org/ws/2",
    dataPoints: [
      "contributions-editoriales",
      "artistes-ajoutes",
      "albums",
      "labels",
    ],
    targetTopics: ["music-audio"],
    targetCategories: ["music-culture"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Contributeur = passionne encyclopediste.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "bandcamp",
    name: "Bandcamp",
    icon: "bandcamp",
    color: "#1DA0C3",
    authType: "none",
    website: "https://bandcamp.com",
    dataPoints: [
      "albums",
      "tracks",
      "ventes",
      "fans",
      "wishlistes",
      "genres",
    ],
    targetTopics: ["music-audio"],
    targetCategories: ["music-production", "music-collecting", "music-business"],
    signalConfidence: "very_high",
    integrationPhase: 4,
    notes:
      "Pas d'OAuth officiel. Donnees partiellement publiques.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // GAMING (12 plateformes)
  // =========================================================================
  {
    id: "steam",
    name: "Steam",
    icon: "steam",
    color: "#1B2838",
    authType: "oauth2",
    website: "https://store.steampowered.com",
    apiBaseUrl: "https://api.steampowered.com",
    dataPoints: [
      "heures-par-jeu",
      "achievements",
      "jeux-possedes",
      "reviews",
      "groupes",
    ],
    targetTopics: ["gaming"],
    targetCategories: [
      "fps-competitive",
      "rpg-narrative",
      "strategy-4x",
      "mmo-social",
      "retro-collecting",
    ],
    signalConfidence: "high",
    integrationPhase: 2,
    notes:
      "API publique. Heures de jeu = signal engagement fort.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "chess-com",
    name: "Chess.com",
    icon: "chess",
    color: "#769656",
    authType: "public",
    website: "https://chess.com",
    apiBaseUrl: "https://api.chess.com/pub",
    dataPoints: [
      "elo",
      "parties-jour",
      "streak",
      "openings",
      "tournois",
      "puzzles",
    ],
    targetTopics: ["gaming", "sport-health"],
    targetCategories: ["strategy-puzzle"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "100% public sans OAuth. Elo = metrique universelle de skill.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "lichess",
    name: "Lichess",
    icon: "lichess",
    color: "#000000",
    authType: "oauth2",
    website: "https://lichess.org",
    apiBaseUrl: "https://lichess.org/api",
    dataPoints: [
      "elo",
      "parties",
      "ouvertures",
      "puzzles",
      "tournois",
      "streak",
    ],
    targetTopics: ["gaming"],
    targetCategories: ["strategy-puzzle"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "Open source, API complete, donnees riches.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "riot-games",
    name: "Riot Games",
    icon: "riot",
    color: "#D32936",
    authType: "oauth2",
    website: "https://riotgames.com",
    apiBaseUrl: "https://euw1.api.riotgames.com",
    dataPoints: [
      "rang",
      "kda",
      "champions-joues",
      "win-rate",
      "heures",
    ],
    targetTopics: ["gaming"],
    targetCategories: ["fps-competitive"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes: "API officielle. Rang = niveau precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "blizzard",
    name: "Blizzard",
    icon: "blizzard",
    color: "#00AEFF",
    authType: "oauth2",
    website: "https://blizzard.com",
    apiBaseUrl: "https://eu.api.blizzard.com",
    dataPoints: [
      "personnages",
      "achievements",
      "item-level",
      "classements",
    ],
    targetTopics: ["gaming"],
    targetCategories: ["mmo-social", "fps-competitive"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "WoW = signal MMO fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "opendota",
    name: "OpenDota",
    icon: "opendota",
    color: "#6A7C8B",
    authType: "public",
    website: "https://opendota.com",
    apiBaseUrl: "https://api.opendota.com/api",
    dataPoints: [
      "heros-joues",
      "win-rate",
      "gpm",
      "tournois",
      "comportement",
    ],
    targetTopics: ["gaming"],
    targetCategories: ["strategy-4x"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "Entierement public. Donnees precises.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "tracker-gg",
    name: "Tracker.gg",
    icon: "trackergg",
    color: "#1D9BF0",
    authType: "api_key",
    website: "https://tracker.gg",
    apiBaseUrl: "https://public-api.tracker.gg/v2",
    dataPoints: [
      "stats-multi-jeux",
      "rang",
      "kda",
      "win-rate",
    ],
    targetTopics: ["gaming"],
    targetCategories: ["fps-competitive"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Agregateur stats gaming multi-titres.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "boardgamegeek",
    name: "BoardGameGeek",
    icon: "boardgamegeek",
    color: "#FF5100",
    authType: "public",
    website: "https://boardgamegeek.com",
    apiBaseUrl: "https://boardgamegeek.com/xmlapi2",
    dataPoints: [
      "collection",
      "parties-jouees",
      "ratings",
      "listes",
    ],
    targetTopics: ["gaming"],
    targetCategories: ["strategy-puzzle", "tabletop-rpg"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "API XML ancienne mais stable et complete.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "myanimelist",
    name: "MyAnimeList",
    icon: "myanimelist",
    color: "#2E51A2",
    authType: "oauth2",
    website: "https://myanimelist.net",
    apiBaseUrl: "https://api.myanimelist.net/v2",
    dataPoints: [
      "anime-vus",
      "scores",
      "liste",
      "genres",
      "studios",
    ],
    targetTopics: ["gaming", "video-cinema"],
    targetCategories: ["streaming-series", "fiction"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal otaku/weeb precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "anilist",
    name: "AniList",
    icon: "anilist",
    color: "#02A9FF",
    authType: "oauth2",
    website: "https://anilist.co",
    apiBaseUrl: "https://graphql.anilist.co",
    dataPoints: [
      "anime",
      "manga",
      "scores",
      "activite",
      "favoris",
      "genres",
    ],
    targetTopics: ["gaming", "video-cinema"],
    targetCategories: ["streaming-series", "fiction"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "GraphQL complete. Alternative MAL moderne.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "trakt",
    name: "Trakt.tv",
    icon: "trakt",
    color: "#ED1C24",
    authType: "oauth2",
    website: "https://trakt.tv",
    apiBaseUrl: "https://api.trakt.tv",
    dataPoints: [
      "films-vus",
      "series-vues",
      "ratings",
      "listes",
      "historique",
    ],
    targetTopics: ["gaming", "video-cinema", "literature"],
    targetCategories: ["cinephilia", "streaming-series"],
    signalConfidence: "high",
    integrationPhase: 2,
    notes: "Scrobbling films/series. Signal cinephile.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "rawg",
    name: "RAWG",
    icon: "rawg",
    color: "#1C1C1C",
    authType: "api_key",
    website: "https://rawg.io",
    apiBaseUrl: "https://api.rawg.io/api",
    dataPoints: [
      "bibliotheque-jeux",
      "ratings",
      "plateformes",
      "genres",
    ],
    targetTopics: ["gaming"],
    targetCategories: ["rpg-narrative", "fps-competitive", "indie-art-games"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Base de donnees jeux + collection user.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // WEB3 (10 plateformes)
  // =========================================================================
  {
    id: "wallet-siwe",
    name: "Wallet ETH/Base/Arb",
    icon: "ethereum",
    color: "#627EEA",
    authType: "siwe",
    website: "https://ethereum.org",
    dataPoints: [
      "transactions",
      "protocoles-interagis",
      "anciennete",
      "volume",
      "nfts",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: [
      "defi",
      "nft-art",
      "web3-infra-dev",
      "dao-governance",
    ],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Verite absolue on-chain. Alchemy free 300M compute units/mois.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "lens",
    name: "Lens Protocol",
    icon: "lens",
    color: "#ABFE2C",
    authType: "siwe",
    website: "https://lens.xyz",
    apiBaseUrl: "https://api-v2.lens.dev",
    dataPoints: [
      "posts",
      "follows",
      "mirrors",
      "collects",
      "profil",
      "communautes",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: ["web3-social"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "API GraphQL publique. Signal DeSo early adopter.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "farcaster",
    name: "Farcaster / Neynar",
    icon: "farcaster",
    color: "#8A63D2",
    authType: "siwf",
    website: "https://warpcast.com",
    apiBaseUrl: "https://api.neynar.com/v2/farcaster",
    dataPoints: [
      "casts",
      "likes",
      "follows",
      "channels",
      "anciennete",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: ["web3-social"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "API Neynar. Signal web3 social natif.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "ens",
    name: "ENS (Ethereum Name Service)",
    icon: "ens",
    color: "#5298FF",
    authType: "public",
    website: "https://ens.domains",
    dataPoints: [
      "ens-possede",
      "sous-domaines",
      "date-mint",
      "text-records",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: ["btc-maximalism", "web3-social"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Lookup on-chain. ENS = identite stable = +15 pts.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "the-graph",
    name: "The Graph",
    icon: "thegraph",
    color: "#6747ED",
    authType: "public",
    website: "https://thegraph.com",
    dataPoints: [
      "positions-defi",
      "swaps",
      "liquidite",
      "gouvernance-dao",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: ["defi", "dao-governance"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Subgraph par protocole. Donnees on-chain structurees.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "opensea",
    name: "OpenSea",
    icon: "opensea",
    color: "#2081E2",
    authType: "api_key",
    website: "https://opensea.io",
    apiBaseUrl: "https://api.opensea.io/api/v2",
    dataPoints: [
      "nfts-possedes",
      "mintes",
      "vendus",
      "collections-creees",
      "volume",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: ["nft-art"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Distinction createur/collectionneur/trader essentielle.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "zora",
    name: "Zora",
    icon: "zora",
    color: "#5B5BD6",
    authType: "public",
    website: "https://zora.co",
    dataPoints: [
      "nfts-mintes",
      "editions-creees",
      "collectes",
      "revenus",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: ["nft-art"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "API ouverte. Signal createur web3 fort.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "mirror",
    name: "Mirror.xyz",
    icon: "mirror",
    color: "#007AFF",
    authType: "public",
    website: "https://mirror.xyz",
    dataPoints: [
      "articles-publies",
      "editions-mintees",
      "abonnes",
    ],
    targetTopics: ["web3-crypto", "literature"],
    targetCategories: ["web3-social", "blogging-content", "dao-governance"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal rare : writer web3 natif.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "coinbase",
    name: "Coinbase",
    icon: "coinbase",
    color: "#0052FF",
    authType: "oauth2",
    website: "https://coinbase.com",
    apiBaseUrl: "https://api.coinbase.com/v2",
    scopes: ["wallet:user:read"],
    dataPoints: [
      "transactions",
      "assets",
      "earn-quizzes",
      "staking",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: ["defi", "btc-maximalism", "trading-speculation"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Coinbase Earn = signal educatif.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "snapshot",
    name: "Snapshot",
    icon: "snapshot",
    color: "#F3B04E",
    authType: "public",
    website: "https://snapshot.org",
    apiBaseUrl: "https://hub.snapshot.org/graphql",
    dataPoints: [
      "votes-dao",
      "propositions-creees",
      "espaces-suivis",
    ],
    targetTopics: ["web3-crypto"],
    targetCategories: ["dao-governance"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "Signal gouvernance DAO ultra-precis.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // SPORT (6 plateformes uniques)
  // =========================================================================
  {
    id: "strava",
    name: "Strava",
    icon: "strava",
    color: "#FC4C02",
    authType: "oauth2",
    website: "https://strava.com",
    authUrl: "https://www.strava.com/oauth/authorize",
    tokenUrl: "https://www.strava.com/oauth/token",
    apiBaseUrl: "https://www.strava.com/api/v3",
    scopes: ["read", "activity:read"],
    dataPoints: [
      "activites",
      "km",
      "sports",
      "records-perso",
      "defis",
      "segments",
    ],
    targetTopics: ["sport-health"],
    targetCategories: [
      "running-trail",
      "individual-sports",
      "water-sports",
      "winter-sports",
      "racket-sports",
      "sports-science",
    ],
    signalConfidence: "very_high",
    integrationPhase: 1,
    rateLimitInfo: "100 req/15min",
    notes:
      "API complete. Donnees GPS precises. Excellent engagement sportif.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "garmin",
    name: "Garmin Connect",
    icon: "garmin",
    color: "#007CC3",
    authType: "oauth2",
    website: "https://garmin.com",
    apiBaseUrl: "https://apis.garmin.com",
    dataPoints: [
      "pas",
      "sommeil",
      "vo2max",
      "entrainements",
      "hrv",
      "activites",
    ],
    targetTopics: ["sport-health"],
    targetCategories: [
      "running-trail",
      "individual-sports",
      "water-sports",
      "winter-sports",
      "sports-science",
    ],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Donnees sante precises. Signal serieux.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "polar",
    name: "Polar Flow",
    icon: "polar",
    color: "#D40000",
    authType: "oauth2",
    website: "https://polar.com",
    apiBaseUrl: "https://www.polaraccesslink.com/v3",
    dataPoints: [
      "entrainements",
      "frequence-cardiaque",
      "charge",
      "recuperation",
    ],
    targetTopics: ["sport-health"],
    targetCategories: ["running-trail", "individual-sports", "sports-science"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Similaire Garmin.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "wahoo",
    name: "Wahoo",
    icon: "wahoo",
    color: "#0068B5",
    authType: "oauth2",
    website: "https://wahoofitness.com",
    apiBaseUrl: "https://api.wahooligan.com",
    dataPoints: [
      "activites-cyclisme",
      "puissance",
      "vo2max",
      "entrainements",
    ],
    targetTopics: ["sport-health"],
    targetCategories: ["individual-sports"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal cyclisme/triathlon serieux.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "komoot",
    name: "Komoot",
    icon: "komoot",
    color: "#6AA127",
    authType: "oauth2",
    website: "https://komoot.com",
    apiBaseUrl: "https://api.komoot.de/v007",
    dataPoints: [
      "randonnees",
      "tours",
      "highlights",
      "collections",
      "sports",
    ],
    targetTopics: ["sport-health", "nature-environment"],
    targetCategories: ["outdoor-adventure", "running-trail"],
    signalConfidence: "high",
    integrationPhase: 2,
    notes:
      "Signal outdoor/nature. Activites geolocalisees.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "fitbit",
    name: "Fitbit",
    icon: "fitbit",
    color: "#00B0B9",
    authType: "oauth2",
    website: "https://fitbit.com",
    apiBaseUrl: "https://api.fitbit.com/1.2",
    dataPoints: [
      "pas",
      "calories",
      "sommeil",
      "activites",
      "frequence-cardiaque",
    ],
    targetTopics: ["sport-health"],
    targetCategories: ["health-wellness"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal sante quotidienne.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // SOCIAL (6 plateformes)
  // =========================================================================
  {
    id: "reddit",
    name: "Reddit",
    icon: "reddit",
    color: "#FF4500",
    authType: "oauth2",
    website: "https://reddit.com",
    authUrl: "https://www.reddit.com/api/v1/authorize",
    tokenUrl: "https://www.reddit.com/api/v1/access_token",
    apiBaseUrl: "https://oauth.reddit.com",
    scopes: ["identity", "read", "mysubreddits"],
    dataPoints: [
      "karma",
      "subreddits-actifs",
      "anciennete",
      "posts-comments",
      "awards",
    ],
    targetTopics: [
      "tech-dev",
      "gaming",
      "science",
      "sport-health",
      "personal-dev",
    ],
    targetCategories: [
      "strategy-puzzle",
      "ai-ml",
      "fitness",
      "personal-finance",
      "combat-sports",
      "running-trail",
    ],
    signalConfidence: "high",
    integrationPhase: 1,
    rateLimitInfo: "100 req/min",
    notes:
      "Subreddits = mapping niche ultra-precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "discord",
    name: "Discord",
    icon: "discord",
    color: "#5865F2",
    authType: "oauth2",
    website: "https://discord.com",
    authUrl: "https://discord.com/api/oauth2/authorize",
    tokenUrl: "https://discord.com/api/oauth2/token",
    apiBaseUrl: "https://discord.com/api/v10",
    scopes: ["identify", "guilds"],
    dataPoints: [
      "serveurs-rejoints",
      "roles",
      "anciennete",
    ],
    targetTopics: [
      "tech-dev",
      "gaming",
      "web3-crypto",
      "music-audio",
    ],
    targetCategories: ["open-source", "mmo-social", "web3-social"],
    signalConfidence: "high",
    integrationPhase: 0,
    notes:
      "Serveurs = communautes = domaines. Roles = legitimite.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "mastodon",
    name: "Mastodon",
    icon: "mastodon",
    color: "#6364FF",
    authType: "oauth2",
    website: "https://mastodon.social",
    dataPoints: [
      "toots",
      "followers",
      "instances",
      "favoris",
    ],
    targetTopics: ["tech-dev"],
    targetCategories: ["open-source", "cybersecurity"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Instance choisie = signal fort (fosstodon = dev, merveilles = design).",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "bluesky",
    name: "Bluesky",
    icon: "bluesky",
    color: "#0085FF",
    authType: "oauth2",
    website: "https://bsky.app",
    apiBaseUrl: "https://bsky.social/xrpc",
    dataPoints: [
      "posts",
      "follows",
      "listes",
      "starter-packs",
    ],
    targetTopics: ["tech-dev", "web3-crypto"],
    targetCategories: ["open-source", "web3-social"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "AT Protocol ouvert. Starter packs = niches precises.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "tumblr",
    name: "Tumblr",
    icon: "tumblr",
    color: "#001935",
    authType: "oauth1",
    website: "https://tumblr.com",
    apiBaseUrl: "https://api.tumblr.com/v2",
    dataPoints: [
      "posts",
      "tags",
      "reblogged",
      "followers",
    ],
    targetTopics: ["design-creative"],
    targetCategories: ["illustration"],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Tags = niches culturelles precises. API maintenue.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "pinterest",
    name: "Pinterest",
    icon: "pinterest",
    color: "#E60023",
    authType: "oauth2",
    website: "https://pinterest.com",
    apiBaseUrl: "https://api.pinterest.com/v5",
    dataPoints: [
      "boards",
      "pins",
      "categories",
      "followers",
    ],
    targetTopics: ["design-creative", "food-lifestyle"],
    targetCategories: ["home-decor", "fashion-textile", "gastronomy"],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Boards = centres d'interet visuels.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // VIDEO (5 plateformes)
  // =========================================================================
  {
    id: "youtube",
    name: "YouTube",
    icon: "youtube",
    color: "#FF0000",
    authType: "oauth2",
    website: "https://youtube.com",
    authUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    apiBaseUrl: "https://www.googleapis.com/youtube/v3",
    scopes: [
      "https://www.googleapis.com/auth/youtube.readonly",
    ],
    dataPoints: [
      "videos-uploadees",
      "vues",
      "abonnes",
      "chaines-suivies",
      "commentaires",
    ],
    targetTopics: ["video-cinema"],
    targetCategories: ["youtube-content"],
    signalConfidence: "high",
    integrationPhase: 0,
    rateLimitInfo: "10000 unites/jour",
    notes:
      "Donnees createur accessibles. Consommation restreinte.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "twitch",
    name: "Twitch",
    icon: "twitch",
    color: "#9146FF",
    authType: "oauth2",
    website: "https://twitch.tv",
    authUrl: "https://id.twitch.tv/oauth2/authorize",
    tokenUrl: "https://id.twitch.tv/oauth2/token",
    apiBaseUrl: "https://api.twitch.tv/helix",
    scopes: ["user:read:follows"],
    dataPoints: [
      "heures-streamees",
      "followers",
      "subs",
      "jeux",
      "categories",
      "clips",
    ],
    targetTopics: [
      "video-cinema",
      "gaming",
      "performing-arts",
    ],
    targetCategories: [
      "youtube-content",
      "fps-competitive",
      "theater",
      "speedrunning",
      "live-performance",
    ],
    signalConfidence: "very_high",
    integrationPhase: 0,
    notes:
      "API Helix complete. Signal createur live fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "vimeo",
    name: "Vimeo",
    icon: "vimeo",
    color: "#1AB7EA",
    authType: "oauth2",
    website: "https://vimeo.com",
    apiBaseUrl: "https://api.vimeo.com",
    dataPoints: [
      "videos-uploadees",
      "vues",
      "likes",
      "portfolios",
      "collections",
    ],
    targetTopics: ["video-cinema"],
    targetCategories: ["filmmaking", "documentary", "vfx-postprod"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Signal creatif video plus qualitatif que YouTube.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "dailymotion",
    name: "Dailymotion",
    icon: "dailymotion",
    color: "#00AAFF",
    authType: "oauth2",
    website: "https://dailymotion.com",
    apiBaseUrl: "https://api.dailymotion.com",
    dataPoints: [
      "videos-publiees",
      "vues",
      "abonnes",
      "categories",
    ],
    targetTopics: ["video-cinema"],
    targetCategories: ["youtube-content"],
    signalConfidence: "medium",
    integrationPhase: 4,
    notes: "Moins riche que YouTube mais API ouverte.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  // Trakt.tv already listed under Gaming

  // =========================================================================
  // SCIENCE & EDUCATION (8 plateformes)
  // =========================================================================
  {
    id: "orcid",
    name: "ORCID",
    icon: "orcid",
    color: "#A6CE39",
    authType: "oauth2",
    website: "https://orcid.org",
    apiBaseUrl: "https://pub.orcid.org/v3.0",
    dataPoints: [
      "publications",
      "citations",
      "affiliations",
      "subventions",
      "peer-reviews",
    ],
    targetTopics: ["science"],
    targetCategories: ["mathematics", "physics-cosmology", "biology-neuro"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "Standard mondial academique. Signal irrefutable.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "arxiv",
    name: "ArXiv",
    icon: "arxiv",
    color: "#B31B1B",
    authType: "public",
    website: "https://arxiv.org",
    apiBaseUrl: "http://export.arxiv.org/api",
    dataPoints: [
      "papiers-soumis",
      "domaines",
      "co-auteurs",
    ],
    targetTopics: ["science", "tech-dev"],
    targetCategories: ["ai-ml", "physics-cosmology", "mathematics"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "API publique. Soumission de papier = signal academique.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "semantic-scholar",
    name: "Semantic Scholar",
    icon: "semanticscholar",
    color: "#1857B6",
    authType: "api_key",
    website: "https://semanticscholar.org",
    apiBaseUrl: "https://api.semanticscholar.org/graph/v1",
    dataPoints: [
      "publications",
      "citations",
      "co-auteurs",
      "domaines",
    ],
    targetTopics: ["science"],
    targetCategories: ["mathematics", "physics-cosmology", "biology-neuro"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "211M papiers indexes.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "pubmed",
    name: "PubMed",
    icon: "pubmed",
    color: "#326599",
    authType: "public",
    website: "https://pubmed.ncbi.nlm.nih.gov",
    apiBaseUrl: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
    dataPoints: [
      "publications-medicales",
      "citations",
      "mesh-terms",
    ],
    targetTopics: ["science"],
    targetCategories: ["biology-neuro"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "Signal recherche biomedicale precis.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "openlibrary",
    name: "OpenLibrary",
    icon: "openlibrary",
    color: "#3D6B2E",
    authType: "public",
    website: "https://openlibrary.org",
    apiBaseUrl: "https://openlibrary.org/api",
    dataPoints: [
      "livres-lus",
      "listes",
      "reviews",
      "editions",
    ],
    targetTopics: ["science", "literature"],
    targetCategories: ["fiction", "nonfiction"],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Alternative open source Goodreads.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    icon: "wikipedia",
    color: "#000000",
    authType: "public",
    website: "https://wikipedia.org",
    apiBaseUrl: "https://en.wikipedia.org/w/api.php",
    dataPoints: [
      "articles-edites",
      "categories",
      "discussions",
      "anciennete",
    ],
    targetTopics: ["science"],
    targetCategories: ["history-archaeology", "linguistics", "music-culture"],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Contributions = expertise encodee. Categories = niche.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "duolingo",
    name: "Duolingo",
    icon: "duolingo",
    color: "#58CC02",
    authType: "public",
    website: "https://duolingo.com",
    dataPoints: [
      "streak",
      "langues",
      "xp",
      "league",
      "lecons",
    ],
    targetTopics: ["science", "personal-dev"],
    targetCategories: ["linguistics", "mindfulness-spirituality", "learning"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Endpoint non officiel stable. Streak = discipline.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "khan-academy",
    name: "Khan Academy",
    icon: "khanacademy",
    color: "#14BF96",
    authType: "oauth2",
    website: "https://khanacademy.org",
    apiBaseUrl: "https://www.khanacademy.org/api",
    dataPoints: [
      "exercices-completes",
      "cours",
      "badges",
      "progression",
    ],
    targetTopics: ["science"],
    targetCategories: ["mathematics", "physics-cosmology", "learning"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal apprentissage actif.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // BUSINESS (4 plateformes)
  // =========================================================================
  {
    id: "producthunt",
    name: "Product Hunt",
    icon: "producthunt",
    color: "#DA552F",
    authType: "oauth2",
    website: "https://producthunt.com",
    apiBaseUrl: "https://api.producthunt.com/v2/api/graphql",
    dataPoints: [
      "produits-lances",
      "upvotes",
      "commentaires",
      "maker-badge",
      "featured",
    ],
    targetTopics: ["entrepreneurship"],
    targetCategories: ["startup-saas"],
    signalConfidence: "very_high",
    integrationPhase: 1,
    notes:
      "API GraphQL. Featured = validation forte.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "notion",
    name: "Notion",
    icon: "notion",
    color: "#000000",
    authType: "oauth2",
    website: "https://notion.so",
    apiBaseUrl: "https://api.notion.com/v1",
    dataPoints: [
      "workspaces",
      "templates-publies",
      "integrations",
    ],
    targetTopics: ["entrepreneurship"],
    targetCategories: ["productivity-systems", "learning"],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Signal indirect. Templates = maker/consultant.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "todoist",
    name: "Todoist",
    icon: "todoist",
    color: "#E44332",
    authType: "oauth2",
    website: "https://todoist.com",
    apiBaseUrl: "https://api.todoist.com/rest/v2",
    dataPoints: [
      "taches-completees",
      "projets",
      "labels",
      "streaks",
    ],
    targetTopics: ["entrepreneurship", "personal-dev"],
    targetCategories: ["productivity-systems", "habits"],
    signalConfidence: "medium",
    integrationPhase: 3,
    notes:
      "Signal productivite. Karma = engagement.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "linear",
    name: "Linear",
    icon: "linear",
    color: "#5E6AD2",
    authType: "oauth2",
    website: "https://linear.app",
    apiBaseUrl: "https://api.linear.app/graphql",
    dataPoints: [
      "issues",
      "projets",
      "cycles",
      "equipes",
    ],
    targetTopics: ["entrepreneurship", "tech-dev"],
    targetCategories: ["startup-saas", "devops-cloud"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal maker/CTO fort.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // LIFESTYLE (4 plateformes)
  // =========================================================================
  {
    id: "untappd",
    name: "Untappd",
    icon: "untappd",
    color: "#FFC000",
    authType: "oauth2",
    website: "https://untappd.com",
    apiBaseUrl: "https://api.untappd.com/v4",
    dataPoints: [
      "bieres-checkees",
      "brasseries",
      "notes",
      "badges",
      "wish-list",
    ],
    targetTopics: ["food-lifestyle"],
    targetCategories: ["beverages"],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Niche precise. Signal passionne craft beer irrefutable.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "vivino",
    name: "Vivino",
    icon: "vivino",
    color: "#A61F35",
    authType: "oauth2",
    website: "https://vivino.com",
    dataPoints: [
      "vins-notes",
      "cave",
      "wishlist",
      "notes",
      "regions",
    ],
    targetTopics: ["food-lifestyle"],
    targetCategories: ["gastronomy", "wine-spirits"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal passionne vin precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "openfoodfacts",
    name: "OpenFoodFacts",
    icon: "openfoodfacts",
    color: "#341100",
    authType: "public",
    website: "https://openfoodfacts.org",
    apiBaseUrl: "https://world.openfoodfacts.org/api/v2",
    dataPoints: [
      "produits-scannes",
      "contributions",
      "listes",
    ],
    targetTopics: ["food-lifestyle"],
    targetCategories: ["health-wellness", "gastronomy"],
    signalConfidence: "medium",
    integrationPhase: 4,
    notes:
      "Open source. Signal nutritionnel et consommateur conscient.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "yelp",
    name: "Yelp",
    icon: "yelp",
    color: "#D32323",
    authType: "oauth2",
    website: "https://yelp.com",
    apiBaseUrl: "https://api.yelp.com/v3",
    dataPoints: [
      "reviews-postees",
      "categories",
      "check-ins",
    ],
    targetTopics: ["food-lifestyle"],
    targetCategories: ["gastronomy", "beverages"],
    signalConfidence: "medium",
    integrationPhase: 4,
    rateLimitInfo: "500 req/jour",
    notes: "Reviews = signal local et gastronomique.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // CULTURE (4 plateformes uniques — OpenLibrary & Trakt already listed)
  // =========================================================================
  {
    id: "librarything",
    name: "LibraryThing",
    icon: "librarything",
    color: "#251A15",
    authType: "oauth2",
    website: "https://librarything.com",
    apiBaseUrl: "https://www.librarything.com/services/rest",
    dataPoints: [
      "catalogue-livres",
      "tags",
      "reviews",
      "groupes",
    ],
    targetTopics: ["literature"],
    targetCategories: ["fiction", "literary-criticism"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Signal bibliophile.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "pocket",
    name: "Pocket",
    icon: "pocket",
    color: "#EF4056",
    authType: "oauth2",
    website: "https://getpocket.com",
    apiBaseUrl: "https://getpocket.com/v3",
    dataPoints: [
      "articles-sauvegardes",
      "tags",
      "domaines-lus",
      "frequence",
    ],
    targetTopics: ["literature", "entrepreneurship"],
    targetCategories: ["blogging-content", "marketing-growth"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Tags = interets precis. Domaines = niches reelles.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "feedly",
    name: "Feedly",
    icon: "feedly",
    color: "#2BB24C",
    authType: "oauth2",
    website: "https://feedly.com",
    apiBaseUrl: "https://cloud.feedly.com/v3",
    dataPoints: [
      "flux-rss",
      "categories",
      "articles-lus",
      "engagement",
    ],
    targetTopics: ["literature", "entrepreneurship"],
    targetCategories: ["blogging-content", "marketing-growth", "journalism"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Flux RSS = sources = niches. Signal veille pro.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // NATURE (5 plateformes)
  // =========================================================================
  {
    id: "inaturalist",
    name: "iNaturalist",
    icon: "inaturalist",
    color: "#74AC00",
    authType: "oauth2",
    website: "https://inaturalist.org",
    apiBaseUrl: "https://api.inaturalist.org/v1",
    dataPoints: [
      "observations",
      "especes-identifiees",
      "projets",
    ],
    targetTopics: ["nature-environment", "science"],
    targetCategories: [
      "zoology-fauna",
      "biology-neuro",
      "marine",
      "urban-nature",
      "foraging",
    ],
    signalConfidence: "very_high",
    integrationPhase: 2,
    notes:
      "Signal biologiste amateur irrefutable.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "alltrails",
    name: "AllTrails",
    icon: "alltrails",
    color: "#428813",
    website: "https://alltrails.com",
    authType: "oauth2",
    dataPoints: [
      "randonnees-completees",
      "photos",
      "reviews",
      "listes",
    ],
    targetTopics: ["nature-environment", "sport-health"],
    targetCategories: ["outdoor-adventure", "running-trail"],
    signalConfidence: "high",
    integrationPhase: 2,
    notes: "Signal outdoor precis.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "openstreetmap",
    name: "OpenStreetMap",
    icon: "openstreetmap",
    color: "#7EBC6F",
    authType: "oauth2",
    website: "https://openstreetmap.org",
    apiBaseUrl: "https://api.openstreetmap.org/api/0.6",
    dataPoints: [
      "contributions-carto",
      "changesets",
      "notes",
    ],
    targetTopics: ["nature-environment"],
    targetCategories: ["outdoor-adventure", "open-source", "urban-nature"],
    signalConfidence: "medium",
    integrationPhase: 4,
    notes:
      "Contributeur OSM = passionne carto/outdoor/open source.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "wikiloc",
    name: "Wikiloc",
    icon: "wikiloc",
    color: "#60B946",
    authType: "oauth2",
    website: "https://wikiloc.com",
    apiBaseUrl: "https://api.wikiloc.com",
    dataPoints: [
      "traces-gps",
      "trails-partages",
      "sports",
      "zones",
    ],
    targetTopics: ["nature-environment", "sport-health"],
    targetCategories: ["outdoor-adventure", "running-trail", "individual-sports"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes: "Complement Komoot/Strava pour outdoor.",
    isPublicApi: false,
    isFreeAccess: true,
  },

  // =========================================================================
  // NICHE / IRL (3 plateformes)
  // =========================================================================
  {
    id: "meetup",
    name: "Meetup",
    icon: "meetup",
    color: "#F64060",
    authType: "oauth2",
    website: "https://meetup.com",
    apiBaseUrl: "https://api.meetup.com",
    dataPoints: [
      "groupes-rejoints",
      "evenements-assistes",
      "categories",
    ],
    targetTopics: [
      "tech-dev",
      "entrepreneurship",
      "performing-arts",
    ],
    targetCategories: ["marketing-growth", "theater", "open-source"],
    signalConfidence: "high",
    integrationPhase: 3,
    notes:
      "Categories des groupes = interets IRL confirmes.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "eventbrite",
    name: "Eventbrite",
    icon: "eventbrite",
    color: "#F05537",
    authType: "oauth2",
    website: "https://eventbrite.com",
    apiBaseUrl: "https://www.eventbriteapi.com/v3",
    dataPoints: [
      "evenements-crees",
      "billets-achetes",
      "categories",
    ],
    targetTopics: ["entrepreneurship", "performing-arts"],
    targetCategories: ["personal-branding", "comedy", "marketing-growth"],
    signalConfidence: "medium",
    integrationPhase: 4,
    notes:
      "Achat billet = validation interet reel.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "letterboxd",
    name: "Letterboxd",
    icon: "letterboxd",
    color: "#00E054",
    authType: "public",
    website: "https://letterboxd.com",
    dataPoints: [
      "films-notes",
      "listes",
      "reviews",
      "genres",
      "realisateurs",
    ],
    targetTopics: ["video-cinema"],
    targetCategories: ["cinephilia", "film-criticism", "documentary"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes:
      "Pas d'API officielle mais endpoints stables. Signal cinephile top.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // SOCIAL MAJEURS (7 plateformes)
  // =========================================================================
  {
    id: "x-twitter",
    name: "X (Twitter)",
    icon: "twitter",
    color: "#000000",
    authType: "oauth2",
    website: "https://x.com",
    apiBaseUrl: "https://api.x.com/2",
    scopes: ["tweet.read", "users.read"],
    dataPoints: ["tweets", "followers", "engagement", "lists", "spaces"],
    targetTopics: ["tech-dev", "web3-crypto", "entrepreneurship"],
    targetCategories: ["personal-branding", "marketing-growth", "web3-social"],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "API v2 payante. Signal fort pour thought-leadership et crypto.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "instagram",
    name: "Instagram",
    icon: "instagram",
    color: "#E4405F",
    authType: "oauth2",
    website: "https://instagram.com",
    apiBaseUrl: "https://graph.instagram.com",
    dataPoints: ["posts", "followers", "reels", "stories", "engagement"],
    targetTopics: ["design-creative", "food-lifestyle", "performing-arts"],
    targetCategories: [
      "photography",
      "fashion-textile",
      "fashion-streetwear",
      "gastronomy",
      "dance",
    ],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "Graph API via Meta. Fort signal créatif et lifestyle.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "tiktok",
    name: "TikTok",
    icon: "tiktok",
    color: "#010101",
    authType: "oauth2",
    website: "https://tiktok.com",
    apiBaseUrl: "https://open.tiktokapis.com/v2",
    dataPoints: ["videos", "followers", "likes", "shares"],
    targetTopics: ["video-cinema", "performing-arts", "music-audio"],
    targetCategories: [
      "youtube-content",
      "comedy",
      "dance",
      "music-production",
    ],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "API TikTok for Developers. Fort signal créateur vidéo court.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "facebook",
    name: "Facebook",
    icon: "facebook",
    color: "#1877F2",
    authType: "oauth2",
    website: "https://facebook.com",
    apiBaseUrl: "https://graph.facebook.com/v19.0",
    dataPoints: ["pages", "groups", "events", "engagement"],
    targetTopics: ["entrepreneurship", "food-lifestyle"],
    targetCategories: ["marketing-growth", "ecommerce"],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "Graph API. Signal communautaire et business local.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    icon: "linkedin",
    color: "#0A66C2",
    authType: "oauth2",
    website: "https://linkedin.com",
    apiBaseUrl: "https://api.linkedin.com/v2",
    dataPoints: ["posts", "connections", "endorsements", "articles"],
    targetTopics: ["entrepreneurship", "tech-dev", "personal-dev"],
    targetCategories: [
      "personal-branding",
      "coaching-leadership",
      "startup-saas",
      "career",
      "hr-talent",
    ],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "API restrictive. Fort signal professionnel et thought-leadership.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "snapchat",
    name: "Snapchat",
    icon: "snapchat",
    color: "#FFFC00",
    authType: "oauth2",
    website: "https://snapchat.com",
    dataPoints: ["snaps", "stories", "score"],
    targetTopics: ["video-cinema", "food-lifestyle"],
    targetCategories: ["youtube-content", "fashion-streetwear"],
    signalConfidence: "low",
    integrationPhase: 5,
    notes: "API limitée. Signal social faible mais audience large.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "telegram",
    name: "Telegram",
    icon: "telegram",
    color: "#26A5E4",
    authType: "none",
    website: "https://telegram.org",
    dataPoints: ["channels", "groups", "bots"],
    targetTopics: ["web3-crypto", "tech-dev"],
    targetCategories: ["trading-speculation", "dao-governance", "marketing-growth"],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "Bot API publique. Fort signal communauté crypto.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // STREAMING VIDEO (3 plateformes)
  // =========================================================================
  {
    id: "netflix",
    name: "Netflix",
    icon: "netflix",
    color: "#E50914",
    authType: "none",
    website: "https://netflix.com",
    dataPoints: ["watch-history", "ratings", "genres"],
    targetTopics: ["video-cinema"],
    targetCategories: ["streaming-series", "cinephilia"],
    signalConfidence: "low",
    integrationPhase: 5,
    notes: "Pas d'API publique. Signal consommation vidéo.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "disneyplus",
    name: "Disney+",
    icon: "disneyplus",
    color: "#113CCF",
    authType: "none",
    website: "https://disneyplus.com",
    dataPoints: ["watch-history", "watchlist"],
    targetTopics: ["video-cinema"],
    targetCategories: ["cinephilia", "animation"],
    signalConfidence: "low",
    integrationPhase: 5,
    notes: "Pas d'API publique.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "crunchyroll",
    name: "Crunchyroll",
    icon: "crunchyroll",
    color: "#F47521",
    authType: "none",
    website: "https://crunchyroll.com",
    dataPoints: ["watch-history", "watchlist", "ratings"],
    targetTopics: ["video-cinema", "gaming"],
    targetCategories: ["streaming-series", "fiction", "rpg-narrative"],
    signalConfidence: "low",
    integrationPhase: 5,
    notes: "Pas d'API publique. Fort signal anime/manga.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // STREAMING MUSIQUE (2 plateformes)
  // =========================================================================
  {
    id: "apple-music",
    name: "Apple Music",
    icon: "apple-music",
    color: "#FA243C",
    authType: "none",
    website: "https://music.apple.com",
    dataPoints: ["playlists", "listening-history", "library"],
    targetTopics: ["music-audio"],
    targetCategories: [
      "music-culture",
      "music-collecting",
      "vocals",
      "podcast-audio",
    ],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "MusicKit API. Signal consommation musicale.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "tidal",
    name: "Tidal",
    icon: "tidal",
    color: "#000000",
    authType: "oauth2",
    website: "https://tidal.com",
    dataPoints: ["playlists", "listening-history", "favorites"],
    targetTopics: ["music-audio"],
    targetCategories: ["music-culture", "sound-design", "djing"],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "API developer. Audiophile signal.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // E-COMMERCE & MARKETPLACE (3 plateformes)
  // =========================================================================
  {
    id: "amazon",
    name: "Amazon",
    icon: "amazon",
    color: "#FF9900",
    authType: "none",
    website: "https://amazon.com",
    dataPoints: ["orders", "reviews", "wishlists"],
    targetTopics: ["food-lifestyle", "entrepreneurship"],
    targetCategories: ["ecommerce", "collectibles"],
    signalConfidence: "low",
    integrationPhase: 5,
    notes: "Pas d'API consommateur. Signal achat/e-commerce.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "etsy",
    name: "Etsy",
    icon: "etsy",
    color: "#F16521",
    authType: "oauth2",
    website: "https://etsy.com",
    apiBaseUrl: "https://openapi.etsy.com/v3",
    dataPoints: ["shops", "listings", "reviews", "sales"],
    targetTopics: ["design-creative", "food-lifestyle"],
    targetCategories: [
      "diy-making",
      "fashion-streetwear",
      "ecommerce",
      "thrift-vintage",
    ],
    signalConfidence: "high",
    integrationPhase: 4,
    notes: "API Open v3. Signal créateur/artisan.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "shopify",
    name: "Shopify",
    icon: "shopify",
    color: "#96BF48",
    authType: "oauth2",
    website: "https://shopify.com",
    apiBaseUrl: "https://admin.shopify.com/api/2024-01",
    dataPoints: ["stores", "products", "orders"],
    targetTopics: ["entrepreneurship"],
    targetCategories: ["ecommerce", "startup-saas"],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "Admin API. Signal e-commerce entrepreneur.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // SCIENCE & EDUCATION (4 plateformes)
  // =========================================================================
  {
    id: "google-scholar",
    name: "Google Scholar",
    icon: "google-scholar",
    color: "#4285F4",
    authType: "public",
    website: "https://scholar.google.com",
    dataPoints: ["citations", "h-index", "publications"],
    targetTopics: ["science"],
    targetCategories: ["mathematics", "physics-cosmology", "biology-neuro"],
    signalConfidence: "very_high",
    integrationPhase: 5,
    notes: "Pas d'API officielle. Scraping possible. Signal académique top.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "researchgate",
    name: "ResearchGate",
    icon: "researchgate",
    color: "#00CCBB",
    authType: "none",
    website: "https://researchgate.net",
    dataPoints: ["publications", "citations", "rg-score", "reads"],
    targetTopics: ["science"],
    targetCategories: ["physics-cosmology", "biology-neuro", "psychology"],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "Pas d'API publique. Signal académique et réseau chercheurs.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "coursera",
    name: "Coursera",
    icon: "coursera",
    color: "#0056D2",
    authType: "none",
    website: "https://coursera.org",
    dataPoints: ["courses", "certificates", "specializations"],
    targetTopics: ["science", "personal-dev"],
    targetCategories: [
      "ai-ml",
      "linguistics",
      "coaching-leadership",
      "learning",
      "career",
    ],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "Pas d'API publique. Signal formation continue.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "udemy",
    name: "Udemy",
    icon: "udemy",
    color: "#A435F0",
    authType: "none",
    website: "https://udemy.com",
    apiBaseUrl: "https://www.udemy.com/api-2.0",
    dataPoints: ["courses-enrolled", "courses-completed", "reviews"],
    targetTopics: ["personal-dev", "tech-dev"],
    targetCategories: [
      "web-development",
      "ai-ml",
      "coaching-leadership",
      "learning",
      "career",
    ],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "API affiliate. Signal auto-formation.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // LITERATURE & CULTURE (3 plateformes)
  // =========================================================================
  {
    id: "goodreads",
    name: "Goodreads",
    icon: "goodreads",
    color: "#553B08",
    authType: "none",
    website: "https://goodreads.com",
    dataPoints: ["books-read", "ratings", "reviews", "shelves"],
    targetTopics: ["literature"],
    targetCategories: ["fiction", "literary-criticism", "nonfiction"],
    signalConfidence: "very_high",
    integrationPhase: 5,
    notes: "API dépréciée mais endpoints stables. Signal lecteur top.",
    isPublicApi: false,
    isFreeAccess: true,
  },
  {
    id: "medium",
    name: "Medium",
    icon: "medium",
    color: "#000000",
    authType: "oauth2",
    website: "https://medium.com",
    apiBaseUrl: "https://api.medium.com/v1",
    dataPoints: ["articles", "claps", "followers", "publications"],
    targetTopics: ["literature", "tech-dev", "entrepreneurship"],
    targetCategories: ["blogging-content", "startup-saas"],
    signalConfidence: "high",
    integrationPhase: 4,
    notes: "API limitée. Fort signal écriture et thought-leadership.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "substack",
    name: "Substack",
    icon: "substack",
    color: "#FF6719",
    authType: "none",
    website: "https://substack.com",
    dataPoints: ["newsletters", "subscribers", "posts"],
    targetTopics: ["literature", "entrepreneurship"],
    targetCategories: ["blogging-content", "personal-branding", "journalism"],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "Pas d'API publique. Signal newsletter/écriture.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // COLLABORATION & PRODUCTIVITY (2 plateformes)
  // =========================================================================
  {
    id: "slack",
    name: "Slack",
    icon: "slack",
    color: "#4A154B",
    authType: "oauth2",
    website: "https://slack.com",
    apiBaseUrl: "https://slack.com/api",
    dataPoints: ["workspaces", "channels", "messages"],
    targetTopics: ["tech-dev", "entrepreneurship"],
    targetCategories: ["marketing-growth", "startup-saas", "open-source"],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "API riche. Signal collaboration et communauté.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // GAMING STORES (4 plateformes)
  // =========================================================================
  {
    id: "epic-games",
    name: "Epic Games",
    icon: "epic-games",
    color: "#313131",
    authType: "oauth2",
    website: "https://epicgames.com",
    dataPoints: ["games-owned", "achievements", "playtime"],
    targetTopics: ["gaming"],
    targetCategories: ["rpg-narrative", "fps-competitive", "indie-art-games"],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "API Epic Online Services. Signal gamer PC.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "gog",
    name: "GOG",
    icon: "gog",
    color: "#86328A",
    authType: "oauth2",
    website: "https://gog.com",
    apiBaseUrl: "https://api.gog.com",
    dataPoints: ["games-owned", "wishlist", "playtime"],
    targetTopics: ["gaming"],
    targetCategories: ["rpg-narrative", "retro-collecting"],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "API Galaxy. Signal gamer DRM-free/retro.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "playstation",
    name: "PlayStation",
    icon: "playstation",
    color: "#003791",
    authType: "none",
    website: "https://playstation.com",
    dataPoints: ["trophies", "games-played", "playtime"],
    targetTopics: ["gaming"],
    targetCategories: ["rpg-narrative", "sports-games"],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "Pas d'API publique. Signal gamer console.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "xbox",
    name: "Xbox",
    icon: "xbox",
    color: "#107C10",
    authType: "none",
    website: "https://xbox.com",
    dataPoints: ["gamerscore", "achievements", "games-played"],
    targetTopics: ["gaming"],
    targetCategories: ["rpg-narrative", "fps-competitive", "sports-games"],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "Xbox Live API via Microsoft. Signal gamer console.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // WEB3 DeFi (3 plateformes)
  // =========================================================================
  {
    id: "rarible",
    name: "Rarible",
    icon: "rarible",
    color: "#FEDA03",
    authType: "public",
    website: "https://rarible.com",
    apiBaseUrl: "https://api.rarible.org/v0.1",
    dataPoints: ["nfts-created", "nfts-owned", "collections", "sales"],
    targetTopics: ["web3-crypto", "design-creative"],
    targetCategories: ["nft-art", "illustration"],
    signalConfidence: "high",
    integrationPhase: 4,
    notes: "API multichain. Signal NFT créateur et collectionneur.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "uniswap",
    name: "Uniswap",
    icon: "uniswap",
    color: "#FF007A",
    authType: "public",
    website: "https://uniswap.org",
    dataPoints: ["swaps", "liquidity-positions", "volume"],
    targetTopics: ["web3-crypto"],
    targetCategories: ["defi", "trading-speculation"],
    signalConfidence: "very_high",
    integrationPhase: 4,
    notes: "Données on-chain via The Graph. Signal DeFi top.",
    isPublicApi: true,
    isFreeAccess: true,
  },
  {
    id: "aave",
    name: "Aave",
    icon: "aave",
    color: "#B6509E",
    authType: "public",
    website: "https://aave.com",
    dataPoints: ["deposits", "borrows", "health-factor", "positions"],
    targetTopics: ["web3-crypto"],
    targetCategories: ["defi"],
    signalConfidence: "very_high",
    integrationPhase: 4,
    notes: "Données on-chain. Signal DeFi lending.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // SPORT & HEALTH (2 plateformes)
  // =========================================================================
  {
    id: "nike-run-club",
    name: "Nike Run Club",
    icon: "nike",
    color: "#111111",
    authType: "none",
    website: "https://nike.com",
    dataPoints: ["runs", "distance", "streaks", "achievements"],
    targetTopics: ["sport-health"],
    targetCategories: ["running-trail"],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "Pas d'API publique. Signal runner.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "myfitnesspal",
    name: "MyFitnessPal",
    icon: "myfitnesspal",
    color: "#0070D1",
    authType: "oauth2",
    website: "https://myfitnesspal.com",
    dataPoints: ["calories", "macros", "meals", "streaks"],
    targetTopics: ["sport-health", "food-lifestyle"],
    targetCategories: ["health-wellness", "fitness"],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "API Premium. Signal nutrition et fitness.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // MUSIQUE (1 plateforme)
  // =========================================================================
  {
    id: "genius",
    name: "Genius",
    icon: "genius",
    color: "#FFFF64",
    authType: "oauth2",
    website: "https://genius.com",
    apiBaseUrl: "https://api.genius.com",
    dataPoints: ["annotations", "contributions", "iq-score"],
    targetTopics: ["music-audio"],
    targetCategories: ["vocals", "djing", "music-culture"],
    signalConfidence: "high",
    integrationPhase: 4,
    notes: "API publique. Signal connaissance musicale et lyrics.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // CINEMA (2 plateformes)
  // =========================================================================
  {
    id: "imdb",
    name: "IMDb",
    icon: "imdb",
    color: "#F5C518",
    authType: "none",
    website: "https://imdb.com",
    dataPoints: ["ratings", "watchlist", "reviews"],
    targetTopics: ["video-cinema"],
    targetCategories: [
      "film-criticism",
      "streaming-series",
      "cinephilia",
      "documentary",
    ],
    signalConfidence: "high",
    integrationPhase: 5,
    notes: "Pas d'API publique gratuite. Signal cinéphile.",
    isPublicApi: false,
    isFreeAccess: false,
  },
  {
    id: "rotten-tomatoes",
    name: "Rotten Tomatoes",
    icon: "rotten-tomatoes",
    color: "#FA320A",
    authType: "none",
    website: "https://rottentomatoes.com",
    dataPoints: ["ratings", "reviews", "want-to-see"],
    targetTopics: ["video-cinema"],
    targetCategories: ["film-criticism"],
    signalConfidence: "medium",
    integrationPhase: 5,
    notes: "Pas d'API publique. Signal critique cinéma.",
    isPublicApi: false,
    isFreeAccess: false,
  },

  // =========================================================================
  // WEB3 STAKING (1 plateforme)
  // =========================================================================
  {
    id: "lido",
    name: "Lido",
    icon: "lido",
    color: "#00A3FF",
    authType: "public",
    website: "https://lido.fi",
    dataPoints: ["staked-eth", "rewards", "staking-history"],
    targetTopics: ["web3-crypto"],
    targetCategories: ["defi", "web3-infra-dev"],
    signalConfidence: "very_high",
    integrationPhase: 3,
    notes: "Données on-chain. Signal staking Ethereum.",
    isPublicApi: true,
    isFreeAccess: true,
  },

  // =========================================================================
  // GAMING CONSOLES (1 plateforme)
  // =========================================================================
  {
    id: "nintendo",
    name: "Nintendo",
    icon: "nintendo",
    color: "#E60012",
    authType: "none",
    website: "https://nintendo.com",
    dataPoints: ["games-played", "playtime", "online-activity"],
    targetTopics: ["gaming"],
    targetCategories: ["indie-art-games", "sports-games"],
    signalConfidence: "low",
    integrationPhase: 5,
    notes: "Pas d'API publique. Signal gamer Nintendo.",
    isPublicApi: false,
    isFreeAccess: false,
  },
]

// =============================================================================
// HELPERS
// =============================================================================

export const PLATFORM_BY_ID = new Map(
  PLATFORM_CATALOG.map((p) => [p.id, p])
)

export function getPlatformsByTopic(
  topicId: string
): PlatformConfig[] {
  return PLATFORM_CATALOG.filter((p) =>
    p.targetTopics.includes(topicId)
  )
}

export function getPlatformsByPhase(
  phase: IntegrationPhase
): PlatformConfig[] {
  return PLATFORM_CATALOG.filter(
    (p) => p.integrationPhase === phase
  )
}

export function getPlatformsByCategory(
  categoryId: string
): PlatformConfig[] {
  return PLATFORM_CATALOG.filter((p) =>
    p.targetCategories.includes(categoryId)
  )
}

export function getFreePlatforms(): PlatformConfig[] {
  return PLATFORM_CATALOG.filter((p) => p.isFreeAccess)
}

export function getPlatformsForOnboarding(
  categoryIds: string[]
): PlatformConfig[] {
  const matched = PLATFORM_CATALOG.filter((p) =>
    p.targetCategories.some((c) => categoryIds.includes(c))
  )
  const confOrder: Record<SignalConfidence, number> = {
    very_high: 0,
    high: 1,
    medium: 2,
    low: 3,
  }
  return matched.sort((a, b) => {
    const confDiff =
      confOrder[a.signalConfidence] -
      confOrder[b.signalConfidence]
    return confDiff !== 0
      ? confDiff
      : a.integrationPhase - b.integrationPhase
  })
}
